### ISSUE TITLE
AOT: Encountered undefined provider! Error: The Angular AoT build failed.

### ISSUE THREAD

**Issue by huan** [Chatie/app#33]
It's caused by `@chatie/db`: https://github.com/Chatie/db/issues/30

> **Usually this means you have a circular dependencies (might be caused by using 'barrel' index.ts files.**

```shell
$ ionic cordova build browser --prod

? Looks like a fresh checkout! No ./node_modules directory found. Would you like to install project dependencies? Yes
Installing dependencies may take several minutes!
> npm i
✔ Running command - done!
Running app-scripts build: --prod --platform browser --target cordova
[04:17:35]  build prod started ... 
[04:17:35]  clean started ... 
[04:17:35]  clean finished in 1 ms 
[04:17:35]  copy started ... 
[04:17:35]  deeplinks started ... 
[04:17:35]  deeplinks finished in 57 ms 
[04:17:35]  ngc started ... 
[04:17:38]  typescript error 
            Encountered undefined provider! Usually this means you have a circular dependencies (might be caused by 
            using 'barrel' index.ts files. 

Error: The Angular AoT build failed. See the issues above
    at /home/zixia/chatie/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/home/zixia/chatie/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/home/zixia/chatie/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/home/zixia/chatie/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
[04:17:39]  copy finished in 3.40 s 
```

### See Also
* https://github.com/ionic-team/ionic-app-scripts/issues/885
* https://stackoverflow.com/questions/42764013/circular-dependency-when-exporting-a-service-stub-along-library
* https://stackoverflow.com/questions/49713890/angular-lazy-loaded-module-dependencies-encountered-undefined-provider
* https://stackoverflow.com/a/39302282/1123955

**Comment by nblavoie** [comment]
Any news about this issue ?

**Comment by huan** [comment]
Still fighting with it... have no idea about how to fix it, surfing StackOverflow and GitHub issues all day...

**Comment by huan** [comment]
@nblavoie please see https://github.com/Chatie/db/issues/30#issuecomment-380327881
