### ISSUE TITLE
AOT: Function calls are not supported in decorators but 'AuthModule' was called. 

### ISSUE THREAD

**Issue by huan** [Chatie/app#34]
> Error during template compile of 'AppModule' Function calls are not supported in decorators but 'AuthModule' was called. 

```shell
$ npm run ionic:build --aot

> @chatie/app@0.2.20 ionic:build /home/zixia/chatie/app
> ionic-app-scripts build

[02:12:05]  ionic-app-scripts 3.1.8 
[02:12:05]  build dev started ... 
[02:12:05]  clean started ... 
[02:12:05]  clean finished in 1 ms 
[02:12:05]  copy started ... 
[02:12:05]  deeplinks started ... 
[02:12:05]  deeplinks finished in 84 ms 
[02:12:05]  ngc started ... 
[02:12:09]  typescript error 
            Error during template compile of 'AppModule' Function calls are not supported in decorators but 'AuthModule' 
            was called. 

[02:12:09]  ionic-app-script task: "build" 
[02:12:09]  Error: The Angular AoT build failed. See the issues above 
Error: The Angular AoT build failed. See the issues above
    at /home/zixia/chatie/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/home/zixia/chatie/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/home/zixia/chatie/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/home/zixia/chatie/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
```

### See Also

* https://github.com/dherges/ng-packagr/issues/727

**Comment by huan** [comment]
It seems this should be fixed by https://github.com/zixia/auth-angular/issues/1

**Comment by exequielc** [comment]
sorry but where is the fix  ? how can I solve this issue?

**Comment by huan** [comment]
I want to be help but ... I can not remember anything... Because it's too long ago...
